# Pre-commit hooks
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=51200']  # 50MB limit
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: lfs-check
        name: Check LFS patterns
        entry: git lfs ls-files
        language: system
        pass_filenames: false
        always_run: true
